name: Deploy Hexo Blog
on:
  push:
    branches:
      - makai

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true   
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Install Dependencies
        run: |
          npm install hexo-cli -g
          npm install
          
      - name: Check Theme
        run: |
          ls -la themes/cactus/
          echo "Theme files:"
          find themes/cactus/ -type f
          
      - name: Build
        run: |
          hexo clean
          hexo generate
          echo "Generated files:"
          find public/ -type f
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public